### PR TITLE
[Peras 27] Define sensible default values for `PerasParams`

### LINKED ISSUE #1997: Real ChainDB q-s-m test failure reason is masked by an `error` call in `mkPerasParams`
I'm working on a feature that requires me to run the ChainDB quicheck-state-machine tests. I'm getting an expected failure:

```
Test suite storage-test: RUNNING...
ouroboros-storage
  Storage
    ChainDB
      ChainDB q-s-m
        sequential: FAIL (0.32s)
          *** Failed! Falsified (after 74 tests and 8 shrinks):
```

However, instead of the real failure reason, I see an exception caused by the evaluation of an `error` call:

```
          *** Exception running callback:
          perasIgnoranceRounds: not yet defined
          CallStack (from HasCallStack):
            error, called at ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Params.hs:141:9 in ouroboros-consensus-3.0.1.0-inplace:Ouroboros.Consensus.Peras.Params
          Use --quickcheck-replay="(SMGen 15199793947288194575 6673479649164272623,73)" to reproduce.
```

My understanding is that q-s-m is trying to `Show` the state of the model and evaluates the lazy `perasIgnoranceRounds` field of a `PerasParams` value, which is set to an `error` call by `mkPerasParams`.

I expect that all tests failures on `main` will look like this.

### PR DESCRIPTION
**Pull request by geo2a**
Fixes https://github.com/IntersectMBO/ouroboros-consensus/issues/1997

### CODE REVIEW

File: ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Params.hs [hunk 1]
```diff
@@ -136,17 +136,36 @@ data PerasParams = PerasParams
 -- NOTE: in the future this will depend on a concrete 'BlockConfig'.
 mkPerasParams :: PerasParams
 mkPerasParams =
+  -- Many of these parameters are provided with sensible default values for now,
+  -- waiting for a final decision (in a future stage of the project) on the
+  -- exact values to use. See https://github.com/tweag/cardano-peras/issues/97.
+  --
+  -- We set tentatively T_heal to 2B/asc = 600 slots, as the CIP suggests a
+  -- bigO(B/asc) for that value so that sufficient block are produced to
```
Comment (agustinmista) [inline ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Params.hs]: `sufficient block` --> `sufficiently many blocks`?

File: ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Params.hs [hunk 2]
```diff
@@ -136,17 +136,36 @@ data PerasParams = PerasParams
...
+  -- overcome an adversarially boosted block.
+  --
+  -- We also set tentatively perasCertArrivalThreshold (= X in the formal spec)
+  -- to 30 slots (it must be strictly smaller than perasRoundLength)
+  -- See https://github.com/tweag/cardano-peras/issues/88 and
+  -- https://github.com/tweag/cardano-peras/issues/99 for more information on
+  -- this parameter.
+  --
+  -- We also have T_cp = 129 600 and T_cq = 43 200 as per the design document
```
Comment (agustinmista) [inline ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Peras/Params.hs]: Writing 129_600 and 43_200 would be less confusing IMO.

**Review by agustinmista — COMMENTED** [review]
LGTM, only minor suggestions

**Review by agustinmista — APPROVED** [review]

**Review by jasagredo — APPROVED** [review]
