### PR TITLE
Fix bug in `ChainDB.Unit tests`, remove upper bound on `hashable-1.4.3.0`

### LINKED ISSUE #272: [BUG] - `hashable-1.4.3.0` breaks `ChainDB.Unit` tests
**Internal/External**
Internal

**Summary**
#271 updates the index-state to `2023-08-02` for both hackage and CHaP. This brings in a new `hashable-1.4.3.0` version (where previously, we were using `hashable-1.4.2.0`), which results in test failures: 

```
ouroboros-storage
  Storage
    ChainDB
      Unit tests
        Follower switches to new chain
          model:  FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:238:
            Rollback to wrong point
            	 Expected: At (Block {blockPointSlot = SlotNo 0, blockPointHash = TestHeaderHash (-6942406852547452771)})
            	 Actual: At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash 2415637116744329166})
            Use -p '/Follower switches to new chain/&&/model/' to rerun this test only.
          system: FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:238:
            Rollback to wrong point
            	 Expected: At (Block {blockPointSlot = SlotNo 0, blockPointHash = TestHeaderHash (-6942406852547452771)})
            	 Actual: At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash 2415637116744329166})
            Use -p '/Follower switches to new chain/&&/system/' to rerun this test only.

2 out of 2 tests failed (0.00s)
```

As a temporary fix, #271 puts a strict, exclusive upper bound on `1.4.3.0`. We should investigate why this new version is triggering the test failure.

**Steps to reproduce**
1. Go to #271, or `main` if #271 is merged.
2. Run `cabal run --allow-newer="hashable" --constraint="hashable==1.4.3.0" storage-test -- -p "Follower switches to new chain" `
3. See error

**Expected behavior**
Tests should pass with `hashable-1.4.3.0`. A minor version bump like going from `1.4.2.0` to `1.4.3.0` would not be expected to break anything.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 22.04
- Consensus version: #271

**Screenshots and attachments**
*NA*

**Additional context**
Comparing freeze files on #271 with and without enabling `hashable-1.4.3.0` shows that `hashable` is the only dependency that changes from `hashable-1.4.2.0` to `hashable-1.4.3.0`. To reproduce:
1. Go to #271, or `main` if #271 is merged.
2. Run `cabal freeze`, store `cabal.project.freeze` somewhere.
3. Run `cabal freeze --allow-newer="hashable" --constraint="hashable==1.4.3.0"`, store `cabal.project.freeze` somewhere.
4. Diff `cabal.project.freeze` files from steps 2 and 3.

### PR DESCRIPTION
**Pull request by jorisdral**
# Description

Closes #272.

A bug in the "Follower switches to new chain" test was revealed by a change in `hashable-1.4.3.0`. The bug in the test was a typo, which resulted in **not** creating the following expected chain:
```
    G --- b1 --- b2
            \
             \--- b3 -- b4
```
where we expect to switch to the fork `[b3, b4]`. Instead, the typo resulted in creating the following chain:
```
    G --- b1 --- b2
            \
             \--- b3
              \
               \--- b4
```
This wasn't causing the test to fail previously since `b3` was still on the preferred chain: the tiebreaker for picking `b2`, `b3` or `b4` relied on their header hashes, and `b3`'s header was preferred over both `b2`'s and `b4`'s header. `hashable-1.4.3.0` changed how bits are mixed, and as such it changed header hashes, so now `b2`'s header was preferred. 

Fixing the typo fixes the test.

### Hashes
With `hashable-1.4.2.0`:
```
blockPoint b2 = At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash (-9024026317192558580)})
blockPoint b3 = At (Block {blockPointSlot = SlotNo 2, blockPointHash = TestHeaderHash 6123023101281112798})
blockPoint b4 = At (Block {blockPointSlot = SlotNo 3, blockPointHash = TestHeaderHash 5500770988133767813})
```
With `hashable-1.4.3.0`:
```
blockPoint b2 = At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash 2415637116744329166})
blockPoint b3 = At (Block {blockPointSlot = SlotNo 2, blockPointHash = TestHeaderHash (-3472533029700698941)})
blockPoint b4 = At (Block {blockPointSlot = SlotNo 3, blockPointHash = TestHeaderHash (-3554547504183729870)})
```

### CODE REVIEW

File: ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs [hunk 1]
```diff
@@ -98,14 +98,14 @@ followerSwitchesToNewChain
...
+    b1 <- addBlock $ firstBlock 0 $ fork 0     -- b1 on top of G
+    b2 <- addBlock $ mkNextBlock b1 1 $ fork 0 -- b2 on top of b1
     f <- newFollower
     followerForward f [blockPoint b2] >>= \case
       Right (Just pt) -> assertEqual (blockPoint b2) pt "Expected to be at b2"
       _               -> failWith "Expecting a success"
-    b3 <- addBlock $ mkNextBlock b1 2 $ fork 1
-    void $ addBlock $ mkNextBlock b1 3 $ fork 1 -- b4
+    b3 <- addBlock $ mkNextBlock b1 2 $ fork 1  -- b3 on top of b1
+    void $ addBlock $ mkNextBlock b3 3 $ fork 1 -- b4 on top of b3
```
Comment (amesgen) [inline ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:108]: Optional: We could add a check that the follower reports `AddBlock b4` after it reported `b3`. This would have caught the previously buggy implementation (as `b4` was then *not* extending `b4`).

**Review by amesgen — APPROVED** [review]
Great catch!

File: ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs (hunk 1 above)
Comment (jorisdral) [reply ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:108]: Bug re-introduced, before your suggestion:

```
... $ cabal run --constraint="hashable==1.4.2.0" storage-test -- -p "Follower switches to new chain"
ouroboros-storage
  Storage
    ChainDB
      Unit tests
        Follower switches to new chain
          model:  OK
          system: OK

All 2 tests passed (0.00s)
```

Bug re-introduced, after adding your suggestion:

```
... $ cabal run --constraint="hashable==1.4.2.0" storage-test -- -p "Follower switches to new chain"
ouroboros-storage
  Storage
    ChainDB
      Unit tests
        Follower switches to new chain
          model:  FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:242:
            Expecting instruction to add a block
            Use -p '/Follower switches to new chain/&&/model/' to rerun this test only.
          system: FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:242:
            Expecting instruction to add a block
            Use -p '/Follower switches to new chain/&&/system/' to rerun this test only.

2 out of 2 tests failed (0.00s)

... $ cabal run --constraint="hashable==1.4.3.0" storage-test -- -p "Follower switches to new chain"
ouroboros-storage
  Storage
    ChainDB
      Unit tests
        Follower switches to new chain
          model:  FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:242:
            Rollback to wrong point
            	 Expected: At (Block {blockPointSlot = SlotNo 0, blockPointHash = TestHeaderHash (-6942406852547452771)})
            	 Actual: At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash 2415637116744329166})
            Use -p '/Follower switches to new chain/&&/model/' to rerun this test only.
          system: FAIL
            test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs:242:
            Rollback to wrong point
            	 Expected: At (Block {blockPointSlot = SlotNo 0, blockPointHash = TestHeaderHash (-6942406852547452771)})
            	 Actual: At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash 2415637116744329166})
            Use -p '/Follower switches to new chain/&&/system/' to rerun this test only.

2 out of 2 tests failed (0.00s)
```

Now fixing the bug:

```
... $ cabal run --constraint="hashable==1.4.3.0" storage-test -- -p "Follower switches to new chain"
ouroboros-storage
  Storage
    ChainDB
      Unit tests
        Follower switches to new chain
          model:  OK
          system: OK

All 2 tests passed (0.00s)
```
